# Data Collection y Exploratorio Inicial

[DATASET](#DATASET)
1. [Mediante la API](#1.-Mediante-la-API)
2. [csv desde la web](#2.-csv-desde-la-web)

[Exploratorio Inicial](#Exploratorio-Inicial)

## DATASET

He investigado la web de la NASA y he descubierto que dispone de una API para recuperar tablas. Vamos a ver dos maneras de recuperar las tablas que necesitamos para nuestro análisis. Además, he descubierto que desde que descargué la primera vez el dataset, se han añadido 6 planetas más a la base de datos de la NASA, por lo que tal vez sea buena idea considerar la opción de la API para recuperar el dataset más actualizado.

### 1. Mediante la API

Recuperamos los datos de la [API de la NASA](https://exoplanetarchive.ipac.caltech.edu/docs/program_interfaces.html)  

El dataset es de la tabla Planetary Systems Composite Data

In [1]:
import requests
import pandas as pd

Generamos la url y descargamos los datos

In [2]:
tabla = 'query=select+*+from+pscomppars' # Tabla PSCompPars
tipo = 'format=json'
url_nasa = f'https://exoplanetarchive.ipac.caltech.edu/TAP/sync'

url = url_nasa + '?' + tabla + '&' + tipo
print(url)
response = requests.get(url)

if response.status_code == 200:  # Código 200 indica una respuesta exitosa.
    exoplanets_json = response.json()  # Analizar la respuesta JSON.
    print('Respuesta OK -', response.status_code)
else:
    print("Error en la solicitud: ", response.status_code)

https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+*+from+pscomppars&format=json
Respuesta OK - 200

Guardamos el json descargado en un dataframe y ordenamos por el nombre del exoplaneta. Después añadimos la columna 'rowid' que sirve como índice y reseteamos índice implícito para que quede ordenado

In [3]:
PSCP_api = pd.DataFrame(exoplanets_json)

PSCP_api = PSCP_api.sort_values('pl_name')

PSCP_api['rowid'] = range(1, len(PSCP_api) + 1)
PSCP_api = PSCP_api[['rowid'] + PSCP_api.columns[:-1].tolist()]

PSCP_api = PSCP_api.reset_index(drop=True)
PSCP_api

,rowid,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,...,cb_flag,pl_angsep,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_angsep_reflink,pl_ndispec
0,1,3.11485,11 Com b,b,2.56666,11 Com,HD 107383,HIP 60202,TIC 72437047,2008-01,...,0,12.60,None,None,0.0,None,12.6,None,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
1,2,3.10904,11 UMi b,b,2.57407,11 UMi,HD 136726,HIP 74793,TIC 230061010,2009-10,...,0,12.20,None,None,0.0,None,12.2,None,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
2,3,3.10905,14 And b,b,2.62086,14 And,HD 221345,HIP 116076,TIC 333225860,2008-12,...,0,10.30,None,None,0.0,None,10.3,None,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
3,4,3.10906,14 Her b,b,2.57735,14 Her,HD 145675,HIP 79248,TIC 219483057,2003-01,...,0,158.00,None,None,0.0,None,158,None,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
4,5,3.10907,16 Cyg B b,b,2.46258,16 Cyg B,HD 186427,HIP 96901,TIC 27533327,1997-07,...,0,78.50,None,None,0.0,None,78.5,None,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6148,6149,3.11434,ups And b,b,2.54308,ups And,HD 9826,HIP 7513,TIC 189576919,1997-01,...,0,4.42,None,None,0.0,None,4.42,None,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
6149,6150,3.11435,ups And c,c,2.54308,ups And,HD 9826,HIP 7513,TIC 189576919,1999-12,...,0,61.70,None,None,0.0,None,61.7,None,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
6150,6151,3.11436,ups And d,d,2.54308,ups And,HD 9826,HIP 7513,TIC 189576919,1999-12,...,0,187.00,None,None,0.0,None,187,None,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
6151,6152,3.13036,ups Leo b,b,2.573013,ups Leo,NaN,NaN,TIC 49430557,2021-12,...,0,22.40,None,None,0.0,None,22.4,None,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
6152,6153,3.11396,xi Aql b,b,2.58692,xi Aql,HD 188310,HIP 97938,TIC 375464367,2008-06,...,0,11.10,None,None,0.0,None,11.1,None,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0

Creamos archivo csv en local para no realizar la descarga cada vez (2-5 minutos de descarga)

In [4]:
PSCP_api.to_csv('../data/pscomppars_API.csv', sep=',', index=False)

### 2. csv desde la web

Por otro lado, podemos descargarnos un dataset de sistemas planetarios de la web de [NASA Exoplanet Archive](http://exoplanetarchive.ipac.caltech.edu)

In [5]:
# Sistemas planetarios
PSCompPars = pd.read_csv('../data/PSCompPars_2026.03.31_03.43.51.csv') # Ruta lógica desde donde se encuentra el dataset

C:\Users\urkow\AppData\Local\Temp\ipykernel_16076\3329884499.py:2: DtypeWarning: Columns (0: pl_insol_reflink, 1: pl_eqt_reflink, 2: pl_orbincl_reflink, 3: pl_imppar_reflink, 4: pl_trandep_reflink, 5: pl_trandur_reflink, 6: pl_ratdor_reflink, 7: pl_ratror_reflink, 8: pl_occdep_reflink, 9: pl_projobliq_reflink, 10: pl_trueobliq_reflink) have mixed types. Specify dtype option on import or set low_memory=False.
  PSCompPars = pd.read_csv('../data/PSCompPars_2026.03.31_03.43.51.csv') # Ruta lógica desde donde se encuentra el dataset

This file was produced by the [NASA Exoplanet Archive](http://exoplanetarchive.ipac.caltech.edu)  
  Tue Mar 31 03:43:51 2026
El dataset recuperado de la tabla [Planetary Systems Composite Data](https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblView/nph-tblView?app=ExoTbls&config=PSCompPars)

Por otro lado, podemos ver que la propia web de la NASA advierte que estos datos se componen de muchas fuentes. En nuestro caso, no le daremos importancia a esto, ya que no es un estudio formal, sino un análisis para un proyecto personal del curso.

<img src="../img/NASA_PSCompPars.png" width="800" height="400">

## Exploratorio Inicial

Echamos un primer vistazo a los datos de las dos versiones que hemos recuperado:

In [6]:
import pandas as pd

In [7]:
PSCP_api = pd.read_csv('../data/pscomppars_API.csv') # Ruta lógica desde donde se encuentra el dataset

C:\Users\urkow\AppData\Local\Temp\ipykernel_16076\3554068022.py:1: DtypeWarning: Columns (0: pl_orbinclstr, 1: pl_orbincl_reflink, 2: pl_eqtstr, 3: pl_eqt_reflink, 4: pl_occdepstr, 5: pl_occdep_reflink, 6: pl_insolstr, 7: pl_insol_reflink, 8: sy_umagstr, 9: sy_rmagstr, 10: sy_imagstr, 11: sy_zmagstr, 12: sy_gmagstr, 13: st_rotpstr, 14: pl_projobliqstr, 15: pl_densstr, 16: pl_trandepstr, 17: pl_trandep_reflink, 18: pl_trandurstr, 19: pl_trandur_reflink, 20: pl_radjstr, 21: pl_radestr, 22: pl_ratrorstr, 23: pl_ratror_reflink, 24: pl_trueobliqstr, 25: pl_trueobliq_reflink, 26: sy_icmagstr, 27: pl_ratdorstr, 28: pl_ratdor_reflink, 29: pl_impparstr, 30: pl_imppar_reflink, 31: pl_cmassjstr, 32: pl_cmassj_reflink, 33: pl_cmassestr, 34: pl_cmasse_reflink, 35: pl_projobliq_reflink) have mixed types. Specify dtype option on import or set low_memory=False.
  PSCP_api = pd.read_csv('../data/pscomppars_API.csv') # Ruta lógica desde donde se encuentra el dataset

In [8]:
PSCP_api.head()

,rowid,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,...,cb_flag,pl_angsep,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_angsep_reflink,pl_ndispec
0,1,3.11485,11 Com b,b,2.56666,11 Com,HD 107383,HIP 60202,TIC 72437047,2008-01,...,0,12.6,NaN,NaN,0.0,NaN,12.6,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
1,2,3.10904,11 UMi b,b,2.57407,11 UMi,HD 136726,HIP 74793,TIC 230061010,2009-10,...,0,12.2,NaN,NaN,0.0,NaN,12.2,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
2,3,3.10905,14 And b,b,2.62086,14 And,HD 221345,HIP 116076,TIC 333225860,2008-12,...,0,10.3,NaN,NaN,0.0,NaN,10.3,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
3,4,3.10906,14 Her b,b,2.57735,14 Her,HD 145675,HIP 79248,TIC 219483057,2003-01,...,0,158.0,NaN,NaN,0.0,NaN,158.0,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
4,5,3.10907,16 Cyg B b,b,2.46258,16 Cyg B,HD 186427,HIP 96901,TIC 27533327,1997-07,...,0,78.5,NaN,NaN,0.0,NaN,78.5,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0

In [9]:
PSCompPars.head()

,rowid,pl_name,hostname,pl_letter,hd_name,hip_name,tic_id,gaia_dr2_id,gaia_dr3_id,sy_snum,...,sy_kepmagerr1,sy_kepmagerr2,sy_kepmag_reflink,pl_nnotes,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,pl_ndispec
0,1,11 Com b,11 Com,b,HD 107383,HIP 60202,TIC 72437047,Gaia DR2 3946945413106333696,Gaia DR3 3946945413106333696,2,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,2,1,2,0,0,0,0
1,2,11 UMi b,11 UMi,b,HD 136726,HIP 74793,TIC 230061010,Gaia DR2 1696798367260229376,Gaia DR3 1696798367260229376,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0,1,1,0,0,0,0
2,3,14 And b,14 And,b,HD 221345,HIP 116076,TIC 333225860,Gaia DR2 1920113512486282240,Gaia DR3 1920113512486282240,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,0,1,1,0,0,0,0
3,4,14 Her b,14 Her,b,HD 145675,HIP 79248,TIC 219483057,Gaia DR2 1385293808145621504,Gaia DR3 1385293808145621504,1,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,1,1,4,1,0,0,0
4,5,16 Cyg B b,16 Cyg B,b,HD 186427,HIP 96901,TIC 27533327,Gaia DR2 2135550755683407232,Gaia DR3 2135550755683407232,3,...,NaN,NaN,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,5,1,4,3,0,0,0

Si profundizamos más y revisamos los registros de los dos datasets, vemos que contienen exactamente los mismos exoplanetas.

Revisamos las dimmensiones de los dataframes (filas x columnas)

In [10]:
PSCP_api.shape

(6153, 684)

In [11]:
PSCompPars.shape

(6153, 320)

Las dos tablas contienen muchísimos datos, más de los que necesitaremos (la versión del API tiene aún muchas más columnas que la descarga directa). Es cierto que existe una versión con menos columnas, pero debido a que hay algún dato que usaremos que no está en esa versión reducida, debemos partir de este dataset completo.

Revisamos información sobre las columnas

In [12]:
PSCP_api.describe().T

,count,mean,std,min,25%,50%,75%,max
rowid,6153.0,3077.000000,1776.362435,1.000000,1539.000000,3077.000000,4615.000000,6153.000000
objectid,6153.0,3.260726,0.211449,3.100000,3.122400,3.179900,3.312900,3.999000
hostid,6153.0,2.440925,0.177544,2.100330,2.338290,2.512827,2.572954,2.999700
disc_year,6152.0,2016.990735,4.967697,1992.000000,2014.000000,2016.000000,2021.000000,2026.000000
ra,6153.0,232.922360,91.672676,0.185606,173.301406,284.919421,293.230233,359.974984
...,...,...,...,...,...,...,...,...
pl_angseplim,5808.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
pl_angsepformat,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pl_angsepstr,5808.0,465.337820,13894.238358,0.003530,0.116000,0.283000,1.402500,689000.000000
pl_angsepsymerr,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pl_ndispec,6153.0,0.011214,0.228150,0.000000,0.000000,0.000000,0.000000,8.000000

In [13]:
PSCompPars.describe().T

,count,mean,std,min,25%,50%,75%,max
rowid,6153.0,3077.000000,1776.362435,1.0,1539.0,3077.0,4615.0,6153.0
sy_snum,6153.0,1.103689,0.343016,1.0,1.0,1.0,1.0,4.0
sy_pnum,6153.0,1.773931,1.158205,1.0,1.0,1.0,2.0,8.0
sy_mnum,6153.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
cb_flag,6153.0,0.008776,0.093277,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...
st_nrvc,6153.0,0.205266,0.871428,0.0,0.0,0.0,0.0,12.0
st_nspec,6153.0,0.179587,0.917125,0.0,0.0,0.0,0.0,13.0
pl_nespec,6153.0,0.124817,1.208723,0.0,0.0,0.0,0.0,35.0
pl_ntranspec,6153.0,0.120429,1.148567,0.0,0.0,0.0,0.0,32.0
pl_ndispec,6153.0,0.011214,0.228150,0.0,0.0,0.0,0.0,8.0

Vemos si hay valores nulos:

In [14]:
PSCP_api.info()

<class 'pandas.DataFrame'>
RangeIndex: 6153 entries, 0 to 6152
Columns: 684 entries, rowid to pl_ndispec
dtypes: float64(497), int64(28), object(5), str(154)
memory usage: 32.1+ MB

In [15]:
PSCompPars.info()

<class 'pandas.DataFrame'>
RangeIndex: 6153 entries, 0 to 6152
Columns: 320 entries, rowid to pl_ndispec
dtypes: float64(216), int64(24), str(80)
memory usage: 15.0 MB

Valores únicos de cada columna

In [16]:
PSCP_api.nunique()

rowid                6153
objectid             5807
pl_name              6153
pl_letter               8
hostid               4572
                     ...
pl_angsepformat         0
pl_angsepstr         2358
pl_angsepsymerr         0
pl_angsep_reflink       1
pl_ndispec              7
Length: 684, dtype: int64

In [17]:
PSCompPars.nunique()

rowid           6153
pl_name         6153
hostname        4585
pl_letter          8
hd_name          737
                ...
st_nrvc           13
st_nspec          12
pl_nespec         23
pl_ntranspec      19
pl_ndispec         7
Length: 320, dtype: int64

Tras un primer vistazo, podemos ver que cualquiera de los dos datasets nos vale. Me quedaré con el que obtengo de la API, para tener los datos actualizados sin necesidad de tener que descargar manualmente la tabla.